/* Autogenerated by /usr/bin/halcompile on Fri Jan  8 00:00:33 2021 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:sim_workpiece_ring:Virtuell Workpiece Ring for Probing Simulation");
MODULE_INFO(linuxcnc, "descr:\nAfter tripping home switch, travel in opposite direction is\nrequired (amount set by the hysteresis pin).\nA pin (index-enable) is provided for use when\n\\fB[JOINT_n]HOME_USE_INDEX\\fR is specified to reset\nthe I/O pin \\fBjoint.N.index-enable\\fR.\n");
MODULE_INFO(linuxcnc, "pin:cur_pos_x:float:0:in:Current x-position (typically: joint.n.motor-pos-fb):None:None");
MODULE_INFO(linuxcnc, "pin:cur_pos_y:float:0:in:Current y-position (typically: joint.n.motor-pos-fb):None:None");
MODULE_INFO(linuxcnc, "pin:cur_pos_z:float:0:in:Current z-position (typically: joint.n.motor-pos-fb):None:None");
MODULE_INFO(linuxcnc, "pin:wp_x_pos:float:0:in:Center X-Position of Ring Workpiece where it is placed:0:None");
MODULE_INFO(linuxcnc, "pin:wp_y_pos:float:0:in:Center Y-Position of Ring Workpiece where it is placed:0:None");
MODULE_INFO(linuxcnc, "pin:wp_z_pos:float:0:in:lower Z-Position Workpiece is placed:0:None");
MODULE_INFO(linuxcnc, "pin:wp_z_height:float:0:in:Height of Workpiece in z direction:10:None");
MODULE_INFO(linuxcnc, "pin:wp_radius_inside:float:0:in:Workpiece Inside radius:20:None");
MODULE_INFO(linuxcnc, "pin:wp_radius_outside:float:0:in:Workpiece Outside radius:40:None");
MODULE_INFO(linuxcnc, "pin:tool_length:float:0:in:Length of tool/touch probe in spindle:10:None");
MODULE_INFO(linuxcnc, "pin:tool_probe_on_no:bit:0:out:Tool Probe Signal on - Normal Open:None:None");
MODULE_INFO(linuxcnc, "pin:tool_probe_on_nc:bit:0:out:Tool Probe Signal on - Normal Closed:None:None");
MODULE_INFO(linuxcnc, "funct:_:1:");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_float_t *cur_pos_x;
    hal_float_t *cur_pos_y;
    hal_float_t *cur_pos_z;
    hal_float_t *wp_x_pos;
    hal_float_t *wp_y_pos;
    hal_float_t *wp_z_pos;
    hal_float_t *wp_z_height;
    hal_float_t *wp_radius_inside;
    hal_float_t *wp_radius_outside;
    hal_float_t *tool_length;
    hal_bit_t *tool_probe_on_no;
    hal_bit_t *tool_probe_on_nc;
};
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_float_newf(HAL_IN, &(inst->cur_pos_x), comp_id,
        "%s.cur-pos-x", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->cur_pos_y), comp_id,
        "%s.cur-pos-y", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->cur_pos_z), comp_id,
        "%s.cur-pos-z", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->wp_x_pos), comp_id,
        "%s.wp-x-pos", prefix);
    if(r != 0) return r;
    *(inst->wp_x_pos) = 0;
    r = hal_pin_float_newf(HAL_IN, &(inst->wp_y_pos), comp_id,
        "%s.wp-y-pos", prefix);
    if(r != 0) return r;
    *(inst->wp_y_pos) = 0;
    r = hal_pin_float_newf(HAL_IN, &(inst->wp_z_pos), comp_id,
        "%s.wp-z-pos", prefix);
    if(r != 0) return r;
    *(inst->wp_z_pos) = 0;
    r = hal_pin_float_newf(HAL_IN, &(inst->wp_z_height), comp_id,
        "%s.wp-z-height", prefix);
    if(r != 0) return r;
    *(inst->wp_z_height) = 10;
    r = hal_pin_float_newf(HAL_IN, &(inst->wp_radius_inside), comp_id,
        "%s.wp-radius-inside", prefix);
    if(r != 0) return r;
    *(inst->wp_radius_inside) = 20;
    r = hal_pin_float_newf(HAL_IN, &(inst->wp_radius_outside), comp_id,
        "%s.wp-radius-outside", prefix);
    if(r != 0) return r;
    *(inst->wp_radius_outside) = 40;
    r = hal_pin_float_newf(HAL_IN, &(inst->tool_length), comp_id,
        "%s.tool-length", prefix);
    if(r != 0) return r;
    *(inst->tool_length) = 10;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->tool_probe_on_no), comp_id,
        "%s.tool-probe-on-no", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->tool_probe_on_nc), comp_id,
        "%s.tool-probe-on-nc", prefix);
    if(r != 0) return r;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))_, inst, 1, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
RTAPI_MP_INT(count, "number of sim_workpiece_ring");
char *names = ""; // comma separated names
RTAPI_MP_STRING(names, "names of sim_workpiece_ring");
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("sim_workpiece_ring");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "sim-workpiece-ring.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        int j,idx;
        char *ptr;
        char buf[HAL_NAME_LEN+1];
        ptr = names;
        idx = 0;
        for (i=0,j=0; i <= strlen(names); i++) {
            buf[j] = *(ptr+i);
            if ( (*(ptr+i) == ',') || (*(ptr+i) == 0) ) {
                buf[j] = 0;
                r = export(buf, idx);
                if (*(ptr+i+1) == 0) {break;}
                idx++;
                if(r != 0) {break;}
                j=0;
            } else {
                j++;
            }
        }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef cur_pos_x
#define cur_pos_x (0+*__comp_inst->cur_pos_x)
#undef cur_pos_y
#define cur_pos_y (0+*__comp_inst->cur_pos_y)
#undef cur_pos_z
#define cur_pos_z (0+*__comp_inst->cur_pos_z)
#undef wp_x_pos
#define wp_x_pos (0+*__comp_inst->wp_x_pos)
#undef wp_y_pos
#define wp_y_pos (0+*__comp_inst->wp_y_pos)
#undef wp_z_pos
#define wp_z_pos (0+*__comp_inst->wp_z_pos)
#undef wp_z_height
#define wp_z_height (0+*__comp_inst->wp_z_height)
#undef wp_radius_inside
#define wp_radius_inside (0+*__comp_inst->wp_radius_inside)
#undef wp_radius_outside
#define wp_radius_outside (0+*__comp_inst->wp_radius_outside)
#undef tool_length
#define tool_length (0+*__comp_inst->tool_length)
#undef tool_probe_on_no
#define tool_probe_on_no (*__comp_inst->tool_probe_on_no)
#undef tool_probe_on_nc
#define tool_probe_on_nc (*__comp_inst->tool_probe_on_nc)


#line 32 "sim_workpiece_ring.comp"

FUNCTION(_) {
    bool pin_value=false;
	float distance;

    if (cur_pos_z <= wp_z_pos + wp_z_width + tool_length){
		distance = sqrt(pow ((cur_pos_x-wp_x_pos ) ,2) + pow( (cur_pos_y - wp_y_pos) ,2));
		if ((distance >= wp_radius_inside) &&
       (distance <= wp_radius_outside )) {
            pin_value = true;
		}
	 }

	 tool_probe_on_nc = !pin_value;
	 tool_probe_on_no = pin_value;

    return;
}

static int __comp_get_data_size(void) { return 0; }
